### ISSUE TITLE
Meta: Answer Gabor's Q's; incorporate answers into RFC process doc

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rfcs#121]
Taken from: https://mail.mozilla.org/pipermail/rust-dev/2014-June/010318.html

The below are a good set of questions.  We should strive to update our process documentation so that one can derive the answers to questions like these.

(I expect there to be some answers, perhaps all, posted in the email thread linked above.)
1. [ ] Which of the following does submitting an RFC imply?
   1. We should implement this right away.
   2. We should implement this before 1.0.
   3. We should implement this whenever we feel like it.
2. [ ] Some RFC PRs get closed and tagged with the "postponed" label. Does this
   mean:
   1. It's too early to implement this proposal, or
   2.  it's too early to _evaluate_ this proposal?
3. [ ] Are the designs outlined by RFCs supposed to be "incremental" or
   "final"? I.e.,
   1. First of all we should make this change, without implying anything
      about what happens after that; or
   2. This is how it should look in the final version of the language?
4. If someone submits an RFC, does she imply that "I am planning to
   implement this", or, if an RFC is accepted, does that mean "anyone who
   wants to can feel free to implement this"?
5. The reviewing process is somewhat opaque to me.
   1. [ ] What determines which RFCs get reviewed in a given weekly meeting?
   2. [ ] As an observer, how can I tell which RFCs are considered to be in a
      ready-for-review or will-be-reviewed-next state?
   3. [ ] What if the author of the reviewed RFC isn't a participant in the
      meetings?
   4. [ ] parenthetical: (I might also ask "what determines which RFC PRs get attention from the
      team?", but obviously the answer is "whatever they find interesting".)
